# Generated by Django 5.0.7 on 2024-08-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patients_date_departure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='date_departure',
            field=models.DateField(blank=True, null=True, verbose_name='Дата вибуття'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='end_sentence',
            field=models.DateField(blank=True, null=True, verbose_name='Кінець строку'),
        ),
    ]
