# Generated by Django 5.0.7 on 2024-09-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patients_date_departure_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={'ordering': ['last_name'], 'verbose_name': 'Пацієнт', 'verbose_name_plural': 'Пацієнти'},
        ),
        migrations.AlterField(
            model_name='patients',
            name='term_sentence',
            field=models.DurationField(null=True, verbose_name='Строк'),
        ),
        migrations.AddIndex(
            model_name='patients',
            index=models.Index(fields=['last_name', 'first_name', 'middle_name', 'birth_date'], name='patients_pa_last_na_cd5ed0_idx'),
        ),
    ]
