# Generated by Django 5.0.7 on 2024-09-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patients_options_alter_patients_term_sentence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='Бригада')),
            ],
        ),
    ]
