# Generated by Django 5.0.7 on 2024-11-24 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0007_alter_patients_brigade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата огляду')),
                ('doctor_name', models.CharField(max_length=50, verbose_name="Ім'я лікаря")),
                ('complaints', models.TextField(blank=True, null=True, verbose_name='Скарги')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Діагноз')),
                ('treatment', models.TextField(blank=True, null=True, verbose_name='Призначення')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='patients.patients', verbose_name='Пацієнт')),
            ],
            options={
                'verbose_name': 'Медичний огляд',
                'verbose_name_plural': 'Медичні огляди',
            },
        ),
    ]
